// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC46u52f-deE3cSsOU6QZ-g5TvOI7pCee4',
    appId: '1:875301932333:web:632b448c257b81168b97a4',
    messagingSenderId: '875301932333',
    projectId: 'shan-koe-mee-myanmar',
    authDomain: 'shan-koe-mee-myanmar.firebaseapp.com',
    databaseURL:
        'https://shan-koe-mee-myanmar-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shan-koe-mee-myanmar.firebasestorage.app',
    measurementId: 'G-J29RFKPWTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo66h0t0-7Kn8Jv9SqzAzUsnn2eFAVxsI',
    appId: '1:875301932333:android:27e11f3d2f1163908b97a4',
    messagingSenderId: '875301932333',
    projectId: 'shan-koe-mee-myanmar',
    databaseURL:
        'https://shan-koe-mee-myanmar-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shan-koe-mee-myanmar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnW6locSU2tOum8H6umBkxRM920JJSvrg',
    appId: '1:875301932333:ios:4c83ccf361afe3a98b97a4',
    messagingSenderId: '875301932333',
    projectId: 'shan-koe-mee-myanmar',
    databaseURL:
        'https://shan-koe-mee-myanmar-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shan-koe-mee-myanmar.firebasestorage.app',
    iosBundleId: 'com.thanlar.shanKoeMeeMyanmar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnW6locSU2tOum8H6umBkxRM920JJSvrg',
    appId: '1:875301932333:ios:4c83ccf361afe3a98b97a4',
    messagingSenderId: '875301932333',
    projectId: 'shan-koe-mee-myanmar',
    databaseURL:
        'https://shan-koe-mee-myanmar-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shan-koe-mee-myanmar.firebasestorage.app',
    iosBundleId: 'com.thanlar.shanKoeMeeMyanmar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC46u52f-deE3cSsOU6QZ-g5TvOI7pCee4',
    appId: '1:875301932333:web:d134b8a466657ed88b97a4',
    messagingSenderId: '875301932333',
    projectId: 'shan-koe-mee-myanmar',
    authDomain: 'shan-koe-mee-myanmar.firebaseapp.com',
    databaseURL:
        'https://shan-koe-mee-myanmar-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shan-koe-mee-myanmar.firebasestorage.app',
    measurementId: 'G-M0B96GNYLV',
  );
}
